# spring:
#   application:
#     name: user_manag
#   cloud:
#     config:
#       enabled: false
  # config:
  #   import: optional:configserver:http://localhost:9000

# grpc:
#  client:
#   tenant-service:
#    address:
#     static://localhost:9095
#    negotiationType:
#     plaintext
# server:
#   port: 9003
#spring:
  # datasource:
  #   driver-class-name: org.postgresql.Driver
  #   url: jdbc:postgresql://localhost:5432/postgres
  #   username: postgres
  #   password: chedly
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   database: postgresql
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9003


spring:
  application:
    name: user_manag
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: chedly
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
         spring.json.add.type.info: false
         spring.json.type.mapping: >
            userCreated:com.realtime_monitoring.user_manag.kafka.event.UserCreatedEvent, 
            userUpdated:com.realtime_monitoring.user_manag.kafka.event.UserUpdatedEvent,
            userDeleted:com.realtime_monitoring.user_manag.kafka.event.UserDeletedEvent,
            teamCreated:com.realtime_monitoring.user_manag.kafka.event.TeamCreatedEvent,
            teamUpdated:com.realtime_monitoring.user_manag.kafka.event.TeamUpdatedEvent,
            teamDeleted:com.realtime_monitoring.user_manag.kafka.event.TeamDeletedEvent,
            teamDeleted:com.realtime_monitoring.user_manag.kafka.event.TeamDeletedEvent,
            roleCreated:com.realtime_monitoring.user_manag.kafka.event.RoleCreatedEvent,
            roleUpdated:com.realtime_monitoring.user_manag.kafka.event.RoleUpdatedEvent,
            roleDeleted:com.realtime_monitoring.user_manag.kafka.event.RoleDeletedEvent
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
      
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


grpc:
  server:
    port: 9095