spring:
  application:
    name: user_manag
  config:
    import: optional:configserver:http://localhost:9000


# server:
#   port: 9003
# spring:
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5432/postgres
#     username: postgres
#     password: chedly
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database: postgresql
#     database-platform: org.hibernate.dialect.PostgreSQLDialect